version: "3.8"

services:
  tg-ws-proxy:
    build:
      context: https://github.com/Flowseal/tg-ws-proxy.git
    image: tg-ws-proxy:local
    container_name: tools-tg-ws-proxy-1
    restart: unless-stopped
    environment:
      TG_WS_PROXY_HOST: "0.0.0.0"
      TG_WS_PROXY_PORT: "1443"
      TG_WS_PROXY_SECRET: "${TG_WS_PROXY_SECRET}"
      TG_WS_PROXY_DC_IPS: "1:149.154.175.53 2:149.154.167.51 3:149.154.175.100 4:149.154.167.91 5:91.108.56.130"
    ports:
      - "127.0.0.1:1443:1443"
    networks:
      tools_default:
        ipv4_address: 172.18.200.10

networks:
  tools_default:
    external: true
